name: 008-sync-KingRan/JDJB
on:
  schedule:
  - cron:  "28 */3 * * *"
  workflow_dispatch:
  watch:
    types: started
  #push:
  #  branches: [main]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/KingRan/JDJB.git"
        source_branch: "main"
        destination_branch: "KingRan-JDJB"
        github_token: ${{ secrets.PAT }}
