name: 02-sync-monk-coder/dust-new
on:
  #schedule:
  #- cron:  "02 */2 * * *"
  workflow_dispatch:
  watch:
    types: started
  #push:
  #  branches: [main]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        #source_repo: "https://github.com/nick814/dust.git"
        source_repo: "https://github.com/monk-coder/dust.git"
        source_branch: "dust"
        destination_branch: "dust-new"
        github_token: ${{ secrets.PAT }}
