name: 010-sync-pangbai66
on:
  #schedule:
  #- cron:  "58 */2 * * *"
  workflow_dispatch:
  watch:
    types: started
  #push:
  #  branches: [main]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/pangbai6/pangbai66.git"
        source_branch: "main"
        destination_branch: "pangbai66"
        github_token: ${{ secrets.PAT }}
