
name: 删除历史运行日志
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1-31/7 * *'
# Run monthly, at 00:00 on the 1st day of month.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete_workflow_runs
        uses: smallprogram/delete-workflow-runs@main
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: ${{ secrets.REPO }}
          retain_days: 7
          keep_minimum_runs: 6