name: jd_hundun

on:
  workflow_dispatch:
  schedule:
    - cron: '10 15 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_hundun
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.REPO }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '运行【hundun】'
        run: |
          python3 wait.py 23:59:59.999
      - name: '运行 【测试】'
        run: |
          node hundun/jd_zjd_tuan.js
          node hundun/jdzz.js
          node hundun/ddxw.js
          node hundun/jx_nc.js
          node hundun/dd_factory.js
          node hundun/jx_factory.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}

